{{- if .Values.deployment.enabled }}
### Based on https://github.com/bitnami/charts/blob/main/template/CHART_NAME/templates/deployment.yaml
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  {{- $deploymentLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.deployment.labels .Values.common.labels ) "context" . ) }}
  {{- $deploymentAnnotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.deployment.annotations .Values.common.annotations ) "context" . ) }}
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $deploymentLabels "context" $ ) | nindent 4 }}
  {{- if .Values.common.annotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $deploymentAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.pod.labels .Values.common.labels ) "context" . ) }}
  {{- $podAnnotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.pod.annotations .Values.common.annotations ) "context" . ) }}
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
  {{- if .Values.deployment.strategy }}
  strategy:  {{- include "common.tplvalues.render" (dict "value" .Values.deployment.strategy "context" $ ) | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
      {{- if $podAnnotations }}
      annotations: {{- include "common.tplvalues.render" ( dict "value" $podAnnotations "context" $ ) | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName }}
      {{- end }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- if .Values.pod.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.pod.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.pod.affinityPreset "customLabels" $podLabels "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.pod.antiAffinityPreset "customLabels" $podLabels "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.pod.nodeAffinityPreset.type "key" .Values.pod.nodeAffinityPreset.key "values" .Values.pod.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.pod.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.pod.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.pod.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.pod.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.pod.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.pod.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.pod.securityContext.enabled }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.pod.securityContext "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.pod.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.pod.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if .Values.deployment.initContainers }}
      initContainers: {{- include "common.tplvalues.render" (dict "value" .Values.deployment.initContainers "context" $) | nindent 8 }}
      {{- end }}
{{- end }}
