name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: upload-pages-artifact@v3
        with:
          path: docs
      - uses: actions/deploy-pages@v4
